### ISSUE TITLE
Adding time of event feature?

### ISSUE THREAD

**Issue by kaomoo** [zli117/EInk-Calendar#8]
Hi Zongli
I am a noob in python and is actually know trying to learn in order to complete the EInkCalendar. 
I have gone through the codes and was wondering if it's possible to add timing of the events?

Sorry to post this as issues as I can't find a way to get in touch with you directly.

Regards

Kao
Singapore

**Comment by zli117** [comment]
Sorry for the late replay. Yes, you can. I got all the events here: [https://github.com/zli117/EInk-Calendar/blob/master/model/events.py#L53](https://github.com/zli117/EInk-Calendar/blob/master/model/events.py#L53) in the get_sorted_events function. The function calls Google Calendar API [endpoint](https://developers.google.com/calendar/v3/reference/events/list) using [https://github.com/googleapis/google-api-python-client](https://github.com/googleapis/google-api-python-client). Instead of getting the date, you can get the time of the day as well, by wrapping with datetime object. [Here](https://github.com/zli117/EInk-Calendar/blob/master/view/widgets/event.py#L60) is how I render the datetime to the pixel. Instead of a string of date, you can create a string of date time from the one reveiced above. 

Personally I don't have any interest in adding the time, but feel free to do so on your side.
